# Generated by Django 6.0.1 on 2026-07-19 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_copy_product_image_to_productimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
