# Generated by Django 6.0.1 on 2026-07-24 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_product_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('confirmed', 'Confirmed'), ('dispatched', 'Dispatched'), ('delivered', 'Delivered'), ('review_received', 'Review Received'), ('cancelled', 'Cancelled')], default='new', max_length=20),
        ),
    ]
